# Generated by Django 3.2.2 on 2021-06-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20210609_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=33)),
                ('mobile', models.IntegerField()),
                ('department', models.CharField(default='cardiologist', max_length=23)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
